org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
java_version=21
minecraft_version=1.21.1
loader_version=0.16.14
fabric_version=0.116.17+1.21.1
# mods added to test runs
test_modmenu=11.0.3
test_placeholder_api=2.4.2+1.21
test_figura_version=0.1.6+1.21.1
test_plasmo_version=fabric-1.21.1-2.1.17
# --- replaced by the exporter ---
mod_id=skinmod
mod_name=Custom Mod Skin
mod_version=1.0.0
mod_description=HD skin support
mod_authors=Unknown
mod_license=All Rights Reserved
archives_base_name=skinmod
maven_group=dev.custommodskin
