org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true
net.minecraftforge.gradle.merge-source-sets=true
java_version=21
minecraft_version=1.21.1
forge_version=52.1.16
pack_format=34
# --- replaced by the exporter ---
mod_id=skinmod
mod_name=Custom Mod Skin
mod_version=1.0.0
mod_description=HD skin support
archives_base_name=skinmod
maven_group=dev.custommodskin
# mods added to test runs
test_figura_version=0.1.6+1.21.1
test_plasmo_version=forge-1.21.1-2.1.17
