org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
java_version=17
minecraft_version=1.20.1
forge_version=47.4.26
pack_format=15
# mods added to test runs
test_figura_version=0.1.6+1.20.1
test_plasmo_version=forge-1.20.1-2.1.17
# --- replaced by the exporter ---
mod_id=skinmod
mod_name=Custom Mod Skin
mod_version=1.0.0
mod_description=HD skin support
archives_base_name=skinmod
maven_group=dev.custommodskin
